ops:
  mkdir: 2
  rmdir: 2
  access: 0
  chmod: 0
  chown: 0
  getattr: 0
  readdir: 0
  readlink: 0
  mknod: 0
  statfs: 0
  unlink: 0
  symlink: 0
  rename: 0
  link: 0
  utimens: 0
  open: 0
  create: 0
  read: 0
  write: 0
  truncate: 0
  flush: 0
  release: 0
  fsync: 0
files:
  tmp:
    files:
      1:
        ops: 
          mkdir: 3
      2:
        ops: 
          mkdir: 5
        files:
          4:
            ops: 
              mkdir: 10

enabled: True
