#!/usr/bin/python
# Copyright (c) 2023, mivallion
# Copyright (c) 2015, Nir Soffer
# Copyright (c) 2013, Stavros Korokithakis
# All rights reserved.
#
# Licensed under BSD license, see LICENSE.

import argparse
import atexit
import collections
import contextlib
import errno
import logging
import os
import socket
import sys
import threading
import time
from datetime import datetime

import fuse
import yaml

def _construct_mapping(self, node, deep=False):
    data = self.construct_mapping_org(node, deep)
    return {str(key) : data[key] for key in data}

yaml.SafeLoader.construct_mapping_org = yaml.SafeLoader.construct_mapping
yaml.SafeLoader.construct_mapping = _construct_mapping

def main(args):
    args = parse_args(args)
    logging.basicConfig(
        level=logging.DEBUG if args.debug else logging.INFO,
        format='%(asctime)s %(levelname)s [%(name)s] %(message)s')
    config = Config(args.config)
    Controller(config)
    ops = SlowFS(args.root, config)
    fuse.FUSE(ops, args.mountpoint, foreground=True,
              allow_other=args.allow_other)


def parse_args(args):
    parser = argparse.ArgumentParser(description='A slow filesystem.')
    parser.add_argument('-c', '--config',
                        help='path to configuration file')
    parser.add_argument('--debug', action='store_true',
                        help=('enable extremely detailed and slow debug mode, '
                              'creating gigabytes of logs'))
    parser.add_argument('--allow-other', action='store_true',
                        help=('overrides the security measure restricting '
                              'file access to the filesystem owner, so that '
                              'all users (including root) can access the '
                              'files.'))
    parser.add_argument('root', help='path to real file system')
    parser.add_argument('mountpoint', help='where to mount slowfs')
    return parser.parse_args(args)

class Config(object):
    def __init__(self, path):
        self._path = path
        self.enabled = True
        self.reload()
        self.until_dict = dict()
    
    def reload(self):
        if self._path is None:
            self._config = {}
        else:
            with open(self._path, 'r') as file:
                self._config = yaml.safe_load(file)
        if 'enabled' in self._config:
            self.enabled = self._config['enabled']

    def _get_default(self, name, default):
        return self._config.get('ops', dict()).get(name, default)

    def get(self, name, path='', default=0):
        current_config = self._config
        
        if path == '' or path == '/':
            return self._get_default(name, default)

        if path[0] == '/':
            path = path[1:]

        path_keys = path.split('/')
        if len(path_keys) == 0:
            return self._get_default(name, default)

        key = path_keys[0]
        if key not in current_config.get('files', dict()):
            return self._get_default(name, default)
        
        seconds = self._get_default(name, default)
        for key in path_keys:
            files = current_config.get('files')
            if key not in files:
                return seconds
            path_config = files.get(key)
            path_ops = path_config.get('ops', dict())
            if name in path_ops:
                seconds = path_ops[name]
            current_config = path_config
        
        return seconds
    
    def _set_op(self, ops, name, value):
        ops[name] = value
    
    def set(self, name, value, path=''):
        current_config = self._config

        if path == '' or path == '/':
            ops = current_config.get('ops', dict())
            return self._set_op(ops, name, value)

        if path[0] == '/':
            path = path[1:]
            
        if path[0] == '/':
            path = path[1:]
        
        path_keys = path.split('/')
        if len(path_keys) == 0:
            ops = current_config.get('ops', dict())
            return self._set_op(ops, name, value)
            
        for key in path_keys:
            if 'files' not in current_config:
                current_config['files'] = dict()
            files = current_config.get('files')
            if key not in files:
                files[key] = dict()
            current_config = files.get(key)
        
        if 'ops' not in current_config:
            current_config['ops'] = dict()
        ops = current_config['ops']
            
        return self._set_op(ops, name, value)

class ClientError(Exception):
    pass


class Controller(object):

    SOCK = "control"

    # Response codes
    OK = 0
    INTERNAL_ERROR = 1
    USER_ERROR = 2

    log = logging.getLogger("ctl")

    def __init__(self, config):
        self.config = config
        self.sock = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
        self._remove_sock()
        self.sock.bind(self.SOCK)
        atexit.register(self._remove_sock)
        self.thread = threading.Thread(target=self._run)
        self.thread.daemon = True
        self.thread.start()

    def _run(self):
        try:
            while True:
                self._handle_command()
        except Exception:
            self.log.exception("Unhandled error")
            raise

    def _handle_command(self):
        try:
            msg, sender = self.sock.recvfrom(1024)
        except socket.error as e:
            self.log.error("Error receiving from control socket: %s", e)
            return
        self.log.debug("Received %r from %r", msg, sender)
        try:
            msg = msg.decode("ascii")
        except UnicodeDecodeError:
            self.log.warning("Invalid message %r", msg)
            self._send_msg(
                self.USER_ERROR, "Invalid message %r" % msg, sender)
            return
        cmd, args = self._parse_msg(msg)
        try:
            handle = getattr(self, 'do_' + cmd)
        except AttributeError:
            self.log.warning("Unknown command %r", cmd)
            self._send_msg(
                self.USER_ERROR, "Unknown command %r" % cmd, sender)
            return
        try:
            response = handle(*args)
        except ClientError as e:
            self.log.warning("Client error %s", e)
            self._send_msg(self.USER_ERROR, "Client error %s" % e, sender)
        except Exception:
            self.log.exception("Error handling %r", cmd)
            self._send_msg(self.INTERNAL_ERROR, "Internal error", sender)
        else:
            self._send_msg(self.OK, response, sender)

    def do_help(self, *args):
        """ show this help message """
        commands = sorted((name[3:], getattr(self, name))
                          for name in dir(self)
                          if name.startswith("do_"))
        response = "Available commands:\n"
        for name, func in commands:
            description = func.__doc__.splitlines()[0].strip()
            response += "  %-10s  %s\n" % (name, description)
        return response

    def do_reload(self, *args):
        """ reload configuration """
        self.log.info("Reloading configuration")
        self.config.reload()
        return ""

    def do_enable(self, *args):
        """ enable configuration """
        self.log.info("Enabling configuration")
        self.config.enabled = True
        return ""

    def do_disable(self, *args):
        """ disable configuration """
        self.log.info("Disabling configuration")
        self.config.enabled = False
        return ""

    def _get_set_response(self, name, path):
        res = {
            "op": name,
            "delay": self.config.get(name, path),
        }
        if path in self.config.until_dict and name in self.config.until_dict[path]:
            res['until'] = datetime.fromtimestamp(self.config.until_dict[path][name]).strftime("%Y-%m-%d %H:%M:%S")
        
        return res

    def do_get(self, *args):
        """ get config value """
        if not args:
            raise ClientError("NAME is required")
        name = args[0]

        path = ''
        if len(args) > 1:
            path = args[1]

        return self._get_set_response(name, path)

    def do_set(self, *args):
        """ set config value """
        if len(args) < 2:
            raise ClientError("NAME and VALUE are required")
        name, value = args[:2]
        try:
            value = float(value)
        except ValueError as e:
            raise ClientError("Invalid config value: %s" % e)

        path = ''
        if len(args) > 2:
            path = args[2]

        if len(args) > 3:
            ttl = args[3]
            try:
                ttl = float(ttl)
                self.config.set(name, value, path)
                cur_ts = time.time()
                if path not in self.config.until_dict:
                    self.config.until_dict[path] = dict()
                self.config.until_dict[path][name] = cur_ts + ttl
            except ValueError as e:
                raise ClientError("Invalid time value: %s" % e)

        return self._get_set_response(name, path)

    def do_status(self, *args):
        """ show current status """
        return "Enabled" if self.config.enabled else "Disabled"

    def do_log(self, *args):
        """ change log level """
        if not args:
            raise ClientError("Log level is required")
        name = args[0]
        try:
            level = getattr(logging, name.upper())
        except AttributeError:
            raise ClientError("No such log level %r" % name)
        self.log.info("Setting log level to %r", name)
        logging.getLogger().setLevel(level)
        return ""

    def _parse_msg(self, msg):
        args = msg.split()
        if not args:
            return "help", []
        return args[0], args[1:]

    def _send_msg(self, code, message, sender):
        payload = "%d %s" % (code, message)
        payload = payload.encode("ascii")
        self.sock.sendto(payload, sender)

    def _remove_sock(self):
        try:
            os.unlink(self.SOCK)
        except OSError as e:
            if e.errno != errno.ENOENT:
                raise


class CountedLock(object):

    def __init__(self):
        self.lock = threading.Lock()
        self.count = 0

    def __enter__(self):
        self.lock.acquire()
        return self

    def __exit__(self, *args):
        self.lock.release()


class LockManager(object):

    def __init__(self):
        self._lock = threading.Lock()
        self._busy = collections.defaultdict(CountedLock)

    @contextlib.contextmanager
    def __call__(self, fh):
        with self._lock:
            lock = self._busy[fh]
            lock.count += 1
        try:
            with lock:
                yield
        finally:
            with self._lock:
                lock.count -= 1
                if lock.count == 0:
                    del self._busy[fh]


class SlowFS(fuse.Operations):

    log = logging.getLogger("fs")

    def __init__(self, root, config):
        self.root = os.path.realpath(root)
        self.config = config
        self.locked = LockManager()
    
    def __call__(self, op, path, *args):
        if not hasattr(self, op):
            raise fuse.FuseOSError(errno.EFAULT)
        self.log.debug('-> %s %r %r', op, path, args)
        self._delay(op, path)
        try:
            ret = getattr(self, op)(self.root + path, *args)
        except Exception as e:
            self.log.debug('<- %s %s', op, e)
            raise
        self.log.debug('<- %s %r', op, ret)
        return ret

    def _delay(self, op, path):
        if len(path) > 1 and path[0] == '/':
            path = path[1:]

        if path in self.config.until_dict and op in self.config.until_dict[path]:
            if self.config.until_dict[path][op] < time.time():
                self.config.set(op, 0, path)
                del self.config.until_dict[path][op]

        if self.config.enabled:     
            seconds = self.config.get(op, path)
            if seconds:
                time.sleep(seconds)

    # Filesystem methods

    def access(self, path, mode):
        if not os.access(path, mode):
            raise fuse.FuseOSError(errno.EACCES)

    chmod = os.chmod
    chown = os.chown

    def getattr(self, path, fh=None):
        st = os.lstat(path)
        return {key: getattr(st, key)
                for key in dir(st) if key.startswith('st_')}

    def readdir(self, path, fh):
        return ['.', '..'] + os.listdir(path)

    readlink = os.readlink
    mknod = os.mknod
    rmdir = os.rmdir
    mkdir = os.mkdir

    def statfs(self, path):
        stv = os.statvfs(path)
        return {key: getattr(stv, key)
                for key in dir(stv) if key.startswith('f_')}

    unlink = os.unlink

    def symlink(self, path, target):
        return os.symlink(target, path)

    def rename(self, path, new):
        return os.rename(path, self.root + new)

    def link(self, path, target):
        return os.link(self.root + target, path)

    def utimens(self, path, times=None):
        return os.utime(path, times)

    # File methods

    open = os.open

    def create(self, path, mode, fi=None):
        return os.open(path, os.O_WRONLY | os.O_CREAT, mode)

    def read(self, path, length, offset, fh):
        with self.locked(fh):
            os.lseek(fh, offset, os.SEEK_SET)
            return os.read(fh, length)

    def write(self, path, buf, offset, fh):
        with self.locked(fh):
            os.lseek(fh, offset, os.SEEK_SET)
            return os.write(fh, buf)

    def truncate(self, path, length, fh=None):
        with open(path, 'r+') as f:
            f.truncate(length)

    def flush(self, path, fh):
        return os.fsync(fh)

    def release(self, path, fh):
        return os.close(fh)

    def fsync(self, path, fdatasync, fh):
        return os.fsync(fh)


if __name__ == '__main__':
    main(sys.argv[1:])
